-- Tuello initial schema (Phase 1: foundation).
-- Forward-only. Never edit after merge; add a new migration instead.
--
-- Roles:
--   migrator (whoever runs this file) owns tables.
--   tuello_app       runtime role for api + worker. NOSUPERUSER NOBYPASSRLS. Subject to RLS.
--   tuello_definer   NOLOGIN owner of the few SECURITY DEFINER lookups that must run before a
--                    tenant is known (host resolution, login by email, outbox claiming).
--                    Gets narrow role-scoped policies instead of BYPASSRLS.
-- Login passwords are set outside migrations (infra/postgres/init, or your DB provider).

-- ---------------------------------------------------------------------------------------------
-- Roles and helper schema
-- ---------------------------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tuello_app') THEN
    CREATE ROLE tuello_app NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tuello_definer') THEN
    CREATE ROLE tuello_definer NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  END IF;
END
$$;

-- The migrator must be able to hand function ownership to tuello_definer.
GRANT tuello_definer TO CURRENT_USER;

CREATE SCHEMA IF NOT EXISTS app;
REVOKE ALL ON SCHEMA app FROM PUBLIC;
GRANT USAGE ON SCHEMA app TO tuello_app, tuello_definer;
GRANT USAGE ON SCHEMA public TO tuello_app, tuello_definer;

-- UUID v7: 48-bit unix ms timestamp + version/variant + random. Time-ordered for index locality.
CREATE FUNCTION app.uuid_generate_v7() RETURNS uuid
LANGUAGE plpgsql VOLATILE PARALLEL SAFE AS $$
DECLARE
  ts bytea := substring(int8send(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint) FROM 3);
  b  bytea := ts || substring(uuid_send(gen_random_uuid()) FROM 7 FOR 10);
BEGIN
  b := set_byte(b, 6, (b'0111' || get_byte(b, 6)::bit(4))::bit(8)::int);
  b := set_byte(b, 8, (b'10' || get_byte(b, 8)::bit(6))::bit(8)::int);
  RETURN encode(b, 'hex')::uuid;
END
$$;

-- Tenant context. Raises when missing so that a query without SET LOCAL app.tenant_id fails
-- loudly instead of silently returning nothing.
CREATE FUNCTION app.current_tenant_id() RETURNS uuid
LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
DECLARE
  v text := current_setting('app.tenant_id', true);
BEGIN
  IF v IS NULL OR v = '' THEN
    RAISE EXCEPTION 'tenant context missing: app.tenant_id is not set for this transaction'
      USING ERRCODE = 'TN001';
  END IF;
  RETURN v::uuid;
END
$$;

CREATE FUNCTION app.current_user_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT nullif(current_setting('app.user_id', true), '')::uuid
$$;

GRANT EXECUTE ON FUNCTION app.uuid_generate_v7(), app.current_tenant_id(), app.current_user_id()
  TO tuello_app, tuello_definer;

-- ---------------------------------------------------------------------------------------------
-- Types and tables (generated by `prisma migrate diff`, then reviewed)
-- ---------------------------------------------------------------------------------------------

-- CreateEnum
CREATE TYPE "tenant_status" AS ENUM ('onboarding', 'active', 'suspended');

-- CreateEnum
CREATE TYPE "measurement_unit" AS ENUM ('sqft', 'm2');

-- CreateEnum
CREATE TYPE "role" AS ENUM ('owner', 'admin', 'coordinator', 'shooter', 'editor', 'client', 'brokerage_admin');

-- CreateEnum
CREATE TYPE "membership_status" AS ENUM ('active', 'disabled');

-- CreateEnum
CREATE TYPE "domain_status" AS ENUM ('pending', 'verified', 'failed');

-- CreateEnum
CREATE TYPE "auth_token_purpose" AS ENUM ('verify_email', 'reset_password', 'magic_link');

-- CreateTable
CREATE TABLE "tenants" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" "tenant_status" NOT NULL DEFAULT 'onboarding',
    "time_zone" TEXT NOT NULL DEFAULT 'America/New_York',
    "currency" CHAR(3) NOT NULL DEFAULT 'USD',
    "measurement_unit" "measurement_unit" NOT NULL DEFAULT 'sqft',
    "tax_label" TEXT NOT NULL DEFAULT 'Tax',
    "locale" TEXT NOT NULL DEFAULT 'en',
    "onboarding_completed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenant_domains" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "hostname" TEXT NOT NULL,
    "verification_token" TEXT NOT NULL,
    "status" "domain_status" NOT NULL DEFAULT 'pending',
    "verified_at" TIMESTAMPTZ(6),
    "last_checked_at" TIMESTAMPTZ(6),
    "last_error" TEXT,
    "check_attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "tenant_domains_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenant_brandings" (
    "tenant_id" UUID NOT NULL,
    "logo_key" TEXT,
    "accent_color" CHAR(7),
    "email_sender_name" TEXT,
    "email_reply_to" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tenant_brandings_pkey" PRIMARY KEY ("tenant_id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password_hash" TEXT,
    "email_verified_at" TIMESTAMPTZ(6),
    "password_changed_at" TIMESTAMPTZ(6),
    "totp_secret" TEXT,
    "totp_enabled_at" TIMESTAMPTZ(6),
    "locale" TEXT NOT NULL DEFAULT 'en',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memberships" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "role" NOT NULL,
    "status" "membership_status" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "ip" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invites" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "role" "role" NOT NULL,
    "token_hash" TEXT NOT NULL,
    "invited_by_user_id" UUID,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "accepted_at" TIMESTAMPTZ(6),
    "revoked_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "invites_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_tokens" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "purpose" "auth_token_purpose" NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "consumed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "actor_user_id" UUID,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" UUID,
    "data" JSONB NOT NULL DEFAULT '{}',
    "ip" TEXT,
    "request_id" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outbox_events" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "aggregate_type" TEXT NOT NULL,
    "aggregate_id" UUID,
    "payload" JSONB NOT NULL DEFAULT '{}',
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "locked_until" TIMESTAMPTZ(6),
    "published_at" TIMESTAMPTZ(6),
    "attempts" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_events" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "provider" TEXT NOT NULL,
    "provider_event_id" TEXT NOT NULL,
    "tenant_id" UUID,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "received_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at" TIMESTAMPTZ(6),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,

    CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feature_flags" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID,
    "key" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "tenants_slug_key" ON "tenants"("slug");

-- CreateIndex
CREATE INDEX "tenant_domains_tenant_id_created_at_idx" ON "tenant_domains"("tenant_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "memberships_tenant_id_created_at_idx" ON "memberships"("tenant_id", "created_at");

-- CreateIndex
CREATE INDEX "memberships_tenant_id_role_idx" ON "memberships"("tenant_id", "role");

-- CreateIndex
CREATE INDEX "sessions_tenant_id_user_id_idx" ON "sessions"("tenant_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_tenant_id_token_hash_key" ON "sessions"("tenant_id", "token_hash");

-- CreateIndex
CREATE INDEX "invites_tenant_id_email_idx" ON "invites"("tenant_id", "email");

-- CreateIndex
CREATE INDEX "invites_tenant_id_created_at_idx" ON "invites"("tenant_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "invites_tenant_id_token_hash_key" ON "invites"("tenant_id", "token_hash");

-- CreateIndex
CREATE INDEX "auth_tokens_tenant_id_user_id_purpose_idx" ON "auth_tokens"("tenant_id", "user_id", "purpose");

-- CreateIndex
CREATE UNIQUE INDEX "auth_tokens_tenant_id_token_hash_key" ON "auth_tokens"("tenant_id", "token_hash");

-- CreateIndex
CREATE INDEX "audit_logs_tenant_id_created_at_idx" ON "audit_logs"("tenant_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_logs_tenant_id_entity_type_entity_id_idx" ON "audit_logs"("tenant_id", "entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "outbox_events_tenant_id_occurred_at_idx" ON "outbox_events"("tenant_id", "occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_events_provider_provider_event_id_key" ON "webhook_events"("provider", "provider_event_id");

-- AddForeignKey
ALTER TABLE "tenant_domains" ADD CONSTRAINT "tenant_domains_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tenant_brandings" ADD CONSTRAINT "tenant_brandings_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invites" ADD CONSTRAINT "invites_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invites" ADD CONSTRAINT "invites_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_tokens" ADD CONSTRAINT "auth_tokens_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_tokens" ADD CONSTRAINT "auth_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "outbox_events" ADD CONSTRAINT "outbox_events_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "feature_flags" ADD CONSTRAINT "feature_flags_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------------------------
-- Constraints and indexes Prisma cannot express
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "users" ADD CONSTRAINT "users_email_lowercase" CHECK (email = lower(email));
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_slug_format"
  CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])$' AND slug NOT LIKE '%--%');
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_currency_format" CHECK (currency ~ '^[A-Z]{3}$');
ALTER TABLE "tenant_brandings" ADD CONSTRAINT "tenant_brandings_accent_format"
  CHECK (accent_color IS NULL OR accent_color ~ '^#[0-9A-F]{6}$');
ALTER TABLE "tenant_domains" ADD CONSTRAINT "tenant_domains_hostname_lowercase"
  CHECK (hostname = lower(hostname));
ALTER TABLE "invites" ADD CONSTRAINT "invites_email_lowercase" CHECK (email = lower(email));

-- One live membership per user per tenant.
CREATE UNIQUE INDEX "memberships_tenant_id_user_id_live_key"
  ON "memberships" ("tenant_id", "user_id") WHERE deleted_at IS NULL;

-- One flag row per (tenant or platform default, key).
CREATE UNIQUE INDEX "feature_flags_tenant_id_key_key"
  ON "feature_flags" ("tenant_id", "key") NULLS NOT DISTINCT;

-- Deliberate exceptions to "tenant_id first" (cross-tenant by nature; documented in DECISIONS.md):
-- a hostname may belong to only one tenant platform-wide,
CREATE UNIQUE INDEX "tenant_domains_hostname_live_key"
  ON "tenant_domains" ("hostname") WHERE deleted_at IS NULL;
-- the DNS-check job scans pending domains across tenants,
CREATE INDEX "tenant_domains_pending_check_idx"
  ON "tenant_domains" ("last_checked_at" NULLS FIRST) WHERE status = 'pending' AND deleted_at IS NULL;
-- and the outbox publisher scans unpublished events across tenants.
CREATE INDEX "outbox_events_unpublished_idx"
  ON "outbox_events" ("occurred_at") WHERE published_at IS NULL;

CREATE INDEX "sessions_tenant_id_expires_at_idx" ON "sessions" ("tenant_id", "expires_at");
CREATE INDEX "auth_tokens_tenant_id_expires_at_idx" ON "auth_tokens" ("tenant_id", "expires_at");

-- ---------------------------------------------------------------------------------------------
-- Row-level security: enabled AND forced on every table in public (except Prisma's ledger).
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "tenants"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenants"          FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains"   FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_brandings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_brandings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "users"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users"            FORCE ROW LEVEL SECURITY;
ALTER TABLE "memberships"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memberships"      FORCE ROW LEVEL SECURITY;
ALTER TABLE "sessions"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions"         FORCE ROW LEVEL SECURITY;
ALTER TABLE "invites"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invites"          FORCE ROW LEVEL SECURITY;
ALTER TABLE "auth_tokens"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth_tokens"      FORCE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs"       FORCE ROW LEVEL SECURITY;
ALTER TABLE "outbox_events"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "outbox_events"    FORCE ROW LEVEL SECURITY;
ALTER TABLE "webhook_events"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_events"   FORCE ROW LEVEL SECURITY;
ALTER TABLE "feature_flags"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "feature_flags"    FORCE ROW LEVEL SECURITY;

-- tenants: a tenant sees and changes only itself.
CREATE POLICY tenant_isolation ON "tenants" TO tuello_app
  USING (id = (SELECT app.current_tenant_id()))
  WITH CHECK (id = (SELECT app.current_tenant_id()));

-- Standard tenant isolation for tenant-owned tables.
CREATE POLICY tenant_isolation ON "tenant_domains" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "tenant_brandings" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "memberships" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "sessions" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "invites" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "auth_tokens" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "audit_logs" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
CREATE POLICY tenant_isolation ON "outbox_events" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));

-- users: global identity. Visible to itself and to members of the current tenant
-- (the memberships subquery is itself tenant-filtered by RLS). Only a user updates itself.
CREATE POLICY user_read ON "users" FOR SELECT TO tuello_app
  USING (
    id = app.current_user_id()
    OR EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = users.id)
  );
CREATE POLICY user_insert ON "users" FOR INSERT TO tuello_app
  WITH CHECK ((SELECT app.current_tenant_id()) IS NOT NULL);
CREATE POLICY user_update ON "users" FOR UPDATE TO tuello_app
  USING (id = app.current_user_id())
  WITH CHECK (id = app.current_user_id());

-- feature_flags: platform defaults readable by all tenants; tenant rows only by their tenant.
CREATE POLICY flag_read ON "feature_flags" FOR SELECT TO tuello_app
  USING (tenant_id IS NULL OR tenant_id = (SELECT app.current_tenant_id()));

-- webhook_events: no tuello_app policy at all. Access only through app.record_webhook_event().

-- Narrow policies for the definer role (used only inside the functions below).
CREATE POLICY definer_read ON "tenants" FOR SELECT TO tuello_definer USING (true);
CREATE POLICY definer_read ON "tenant_domains" FOR SELECT TO tuello_definer USING (true);
CREATE POLICY definer_read ON "users" FOR SELECT TO tuello_definer USING (true);
CREATE POLICY definer_read ON "outbox_events" FOR SELECT TO tuello_definer USING (true);
CREATE POLICY definer_update ON "outbox_events" FOR UPDATE TO tuello_definer USING (true) WITH CHECK (true);
CREATE POLICY definer_read ON "webhook_events" FOR SELECT TO tuello_definer USING (true);
CREATE POLICY definer_insert ON "webhook_events" FOR INSERT TO tuello_definer WITH CHECK (true);

-- ---------------------------------------------------------------------------------------------
-- Table privileges. Least privilege; audit_logs and outbox_events are append-only for the app.
-- ---------------------------------------------------------------------------------------------
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON "tenants" TO tuello_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "tenant_domains", "tenant_brandings", "memberships",
  "sessions", "invites", "auth_tokens" TO tuello_app;
GRANT SELECT, INSERT, UPDATE ON "users" TO tuello_app;
GRANT SELECT, INSERT ON "audit_logs", "outbox_events" TO tuello_app;
GRANT SELECT ON "feature_flags" TO tuello_app;

GRANT SELECT ON "tenants", "tenant_domains", "users" TO tuello_definer;
GRANT SELECT, UPDATE ON "outbox_events" TO tuello_definer;
GRANT SELECT, INSERT ON "webhook_events" TO tuello_definer;

-- ---------------------------------------------------------------------------------------------
-- SECURITY DEFINER lookups (owned by tuello_definer). Each returns the minimum it must.
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION app.tenant_by_slug(p_slug text)
RETURNS TABLE (id uuid, slug text, name text, status tenant_status)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT t.id, t.slug, t.name, t.status FROM tenants t
  WHERE t.slug = lower(p_slug) AND t.deleted_at IS NULL
$$;

CREATE FUNCTION app.tenant_by_domain(p_hostname text)
RETURNS TABLE (id uuid, slug text, name text, status tenant_status)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT t.id, t.slug, t.name, t.status
  FROM tenant_domains d JOIN tenants t ON t.id = d.tenant_id
  WHERE d.hostname = lower(p_hostname) AND d.status = 'verified'
    AND d.deleted_at IS NULL AND t.deleted_at IS NULL
$$;

CREATE FUNCTION app.slug_available(p_slug text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT NOT EXISTS (SELECT 1 FROM tenants WHERE slug = lower(p_slug))
$$;

CREATE FUNCTION app.find_user_by_email(p_email text)
RETURNS TABLE (id uuid, name text, password_hash text, email_verified_at timestamptz, totp_enabled boolean)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT u.id, u.name, u.password_hash, u.email_verified_at, u.totp_enabled_at IS NOT NULL
  FROM users u WHERE u.email = lower(p_email) AND u.deleted_at IS NULL
$$;

-- Pending custom domains due for a DNS check: backoff grows with attempts (2^n minutes, max 6 h).
CREATE FUNCTION app.domains_due_for_check(p_limit int)
RETURNS TABLE (id uuid, tenant_id uuid)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  SELECT d.id, d.tenant_id FROM tenant_domains d
  WHERE d.status = 'pending' AND d.deleted_at IS NULL
    AND (d.last_checked_at IS NULL
         OR d.last_checked_at < now() - least(interval '6 hours', interval '1 minute' * power(2, least(d.check_attempts, 12))))
  ORDER BY d.last_checked_at NULLS FIRST
  LIMIT least(p_limit, 500)
$$;

-- Claim a batch of unpublished outbox events with a lease, skipping rows other workers hold.
CREATE FUNCTION app.claim_outbox_events(p_limit int, p_lease_seconds int)
RETURNS SETOF outbox_events
LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  UPDATE outbox_events o
  SET locked_until = now() + make_interval(secs => p_lease_seconds), attempts = o.attempts + 1
  WHERE o.id IN (
    SELECT id FROM outbox_events
    WHERE published_at IS NULL AND (locked_until IS NULL OR locked_until < now())
    ORDER BY occurred_at
    LIMIT least(p_limit, 1000)
    FOR UPDATE SKIP LOCKED
  )
  RETURNING o.*
$$;

CREATE FUNCTION app.mark_outbox_published(p_ids uuid[]) RETURNS integer
LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
  WITH done AS (
    UPDATE outbox_events SET published_at = now(), locked_until = NULL
    WHERE id = ANY(p_ids) AND published_at IS NULL
    RETURNING 1
  )
  SELECT count(*)::int FROM done
$$;

-- Store a verified third-party webhook. duplicate = true when this provider event was seen before.
CREATE FUNCTION app.record_webhook_event(
  p_provider text, p_provider_event_id text, p_type text, p_payload jsonb, p_tenant_id uuid
) RETURNS TABLE (id uuid, duplicate boolean)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_id uuid;
BEGIN
  INSERT INTO webhook_events (provider, provider_event_id, type, payload, tenant_id)
  VALUES (p_provider, p_provider_event_id, p_type, p_payload, p_tenant_id)
  ON CONFLICT (provider, provider_event_id) DO NOTHING
  RETURNING webhook_events.id INTO v_id;
  IF v_id IS NOT NULL THEN
    RETURN QUERY SELECT v_id, false;
  ELSE
    RETURN QUERY SELECT w.id, true FROM webhook_events w
      WHERE w.provider = p_provider AND w.provider_event_id = p_provider_event_id;
  END IF;
END
$$;

ALTER FUNCTION app.tenant_by_slug(text) OWNER TO tuello_definer;
ALTER FUNCTION app.tenant_by_domain(text) OWNER TO tuello_definer;
ALTER FUNCTION app.slug_available(text) OWNER TO tuello_definer;
ALTER FUNCTION app.find_user_by_email(text) OWNER TO tuello_definer;
ALTER FUNCTION app.domains_due_for_check(int) OWNER TO tuello_definer;
ALTER FUNCTION app.claim_outbox_events(int, int) OWNER TO tuello_definer;
ALTER FUNCTION app.mark_outbox_published(uuid[]) OWNER TO tuello_definer;
ALTER FUNCTION app.record_webhook_event(text, text, text, jsonb, uuid) OWNER TO tuello_definer;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA app FROM PUBLIC;
GRANT EXECUTE ON FUNCTION
  app.uuid_generate_v7(), app.current_tenant_id(), app.current_user_id(),
  app.tenant_by_slug(text), app.tenant_by_domain(text), app.slug_available(text),
  app.find_user_by_email(text), app.domains_due_for_check(int),
  app.claim_outbox_events(int, int), app.mark_outbox_published(uuid[]),
  app.record_webhook_event(text, text, text, jsonb, uuid)
TO tuello_app;
GRANT EXECUTE ON FUNCTION app.uuid_generate_v7(), app.current_tenant_id(), app.current_user_id()
  TO tuello_definer;
