-- Phase 2: CRM, service catalog and pricing.
-- Forward-only. Same rules as the init migration: tenant_id NOT NULL + FK, tenant_id leads every
-- index, RLS enabled and forced with the standard tenant_isolation policy.
--
-- Extra guard introduced here: every reference between tenant-owned rows is ALSO a composite
-- foreign key (tenant_id, x_id) -> parent (tenant_id, id), so a row can never point at another
-- tenant's row, even if an API bug passed a foreign id (FK checks bypass RLS).

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------------------------------
-- Types and tables (generated by `prisma migrate diff`, then reviewed)
-- ---------------------------------------------------------------------------------------------

-- CreateEnum
CREATE TYPE "client_status" AS ENUM ('active', 'archived');

-- CreateEnum
CREATE TYPE "saved_view_entity" AS ENUM ('clients', 'brokerages');

-- CreateEnum
CREATE TYPE "import_entity" AS ENUM ('clients', 'brokerages');

-- CreateEnum
CREATE TYPE "import_status" AS ENUM ('awaiting_upload', 'uploaded', 'queued', 'running', 'completed', 'failed');

-- CreateEnum
CREATE TYPE "export_status" AS ENUM ('queued', 'running', 'completed', 'failed');

-- CreateEnum
CREATE TYPE "service_category" AS ENUM ('photo', 'video', 'drone', 'tour_3d', 'floor_plan', 'twilight', 'virtual_staging', 'other');

-- CreateEnum
CREATE TYPE "deliverable_type" AS ENUM ('photos', 'video', 'tour', 'floor_plan', 'document', 'other');

-- CreateEnum
CREATE TYPE "item_kind" AS ENUM ('variant', 'package', 'add_on');

-- CreateEnum
CREATE TYPE "travel_rule_kind" AS ENUM ('territory', 'distance');

-- CreateEnum
CREATE TYPE "coupon_kind" AS ENUM ('percent', 'fixed');

-- CreateTable
CREATE TABLE "brokerages" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "website" TEXT,
    "external_ref" TEXT,
    "price_list_id" UUID,
    "address_line1" TEXT,
    "address_line2" TEXT,
    "city" TEXT,
    "region" TEXT,
    "postal_code" TEXT,
    "country" CHAR(2),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "brokerages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clients" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "brokerage_id" UUID,
    "first_name" TEXT NOT NULL DEFAULT '',
    "last_name" TEXT NOT NULL DEFAULT '',
    "sort_name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "phone_normalized" TEXT,
    "company" TEXT,
    "title" TEXT,
    "status" "client_status" NOT NULL DEFAULT 'active',
    "external_ref" TEXT,
    "price_list_id" UUID,
    "address_line1" TEXT,
    "address_line2" TEXT,
    "city" TEXT,
    "region" TEXT,
    "postal_code" TEXT,
    "country" CHAR(2),
    "merged_into_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_contacts" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "client_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "role" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "notify" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "client_contacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tags" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_tags" (
    "tenant_id" UUID NOT NULL,
    "client_id" UUID NOT NULL,
    "tag_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "client_tags_pkey" PRIMARY KEY ("tenant_id","client_id","tag_id")
);

-- CreateTable
CREATE TABLE "notes" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "client_id" UUID,
    "brokerage_id" UUID,
    "author_user_id" UUID,
    "body" TEXT NOT NULL,
    "pinned" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_activities" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "client_id" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "actor_user_id" UUID,
    "data" JSONB NOT NULL DEFAULT '{}',
    "occurred_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "client_activities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "saved_views" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "entity" "saved_view_entity" NOT NULL,
    "name" TEXT NOT NULL,
    "filters" JSONB NOT NULL DEFAULT '{}',
    "shared" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "saved_views_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "import_jobs" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "entity" "import_entity" NOT NULL,
    "status" "import_status" NOT NULL DEFAULT 'awaiting_upload',
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "file_size" INTEGER NOT NULL,
    "mapping" JSONB,
    "total_rows" INTEGER NOT NULL DEFAULT 0,
    "processed_rows" INTEGER NOT NULL DEFAULT 0,
    "created_count" INTEGER NOT NULL DEFAULT 0,
    "updated_count" INTEGER NOT NULL DEFAULT 0,
    "error_count" INTEGER NOT NULL DEFAULT 0,
    "error_report_key" TEXT,
    "last_error" TEXT,
    "created_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ(6),
    "finished_at" TIMESTAMPTZ(6),

    CONSTRAINT "import_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "export_jobs" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "entity" TEXT NOT NULL,
    "filters" JSONB NOT NULL DEFAULT '{}',
    "status" "export_status" NOT NULL DEFAULT 'queued',
    "file_key" TEXT,
    "row_count" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "created_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at" TIMESTAMPTZ(6),

    CONSTRAINT "export_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skills" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "skills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "services" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "category" "service_category" NOT NULL,
    "duration_minutes" INTEGER NOT NULL,
    "required_skill_id" UUID,
    "deliverable_type" "deliverable_type" NOT NULL,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "services_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_variants" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "service_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "base_price" INTEGER NOT NULL,
    "duration_minutes" INTEGER,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "service_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "packages" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "base_price" INTEGER NOT NULL,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "package_items" (
    "tenant_id" UUID NOT NULL,
    "package_id" UUID NOT NULL,
    "variant_id" UUID NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "package_items_pkey" PRIMARY KEY ("tenant_id","package_id","variant_id")
);

-- CreateTable
CREATE TABLE "add_ons" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "service_id" UUID,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "base_price" INTEGER NOT NULL,
    "duration_minutes" INTEGER NOT NULL DEFAULT 0,
    "max_quantity" INTEGER,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "add_ons_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "property_types" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "property_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "size_bands" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "min_size" INTEGER NOT NULL,
    "max_size" INTEGER,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "size_bands_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "price_rules" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "item_kind" "item_kind" NOT NULL,
    "item_id" UUID NOT NULL,
    "size_band_id" UUID,
    "property_type_id" UUID,
    "price" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "price_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_price_lists" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "default_percent_off_bps" INTEGER NOT NULL DEFAULT 0,
    "waive_travel" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "client_price_lists_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_price_list_items" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "price_list_id" UUID NOT NULL,
    "item_kind" "item_kind" NOT NULL,
    "item_id" UUID NOT NULL,
    "fixed_price" INTEGER,
    "percent_off_bps" INTEGER,

    CONSTRAINT "client_price_list_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "territories" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "postal_prefixes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "territories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "travel_fee_rules" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "kind" "travel_rule_kind" NOT NULL,
    "territory_id" UUID,
    "fee" INTEGER,
    "free_km" INTEGER,
    "per_km" INTEGER,
    "min_fee" INTEGER,
    "max_fee" INTEGER,
    "priority" INTEGER NOT NULL DEFAULT 100,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "travel_fee_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "coupons" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "kind" "coupon_kind" NOT NULL,
    "percent_off_bps" INTEGER,
    "amount_off" INTEGER,
    "min_subtotal" INTEGER,
    "starts_at" TIMESTAMPTZ(6),
    "expires_at" TIMESTAMPTZ(6),
    "max_redemptions" INTEGER,
    "max_per_client" INTEGER,
    "redemption_count" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "coupons_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "coupon_redemptions" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "coupon_id" UUID NOT NULL,
    "client_id" UUID,
    "amount" INTEGER NOT NULL,
    "redeemed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "coupon_redemptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tax_rates" (
    "id" UUID NOT NULL DEFAULT app.uuid_generate_v7(),
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "rate_bps" INTEGER NOT NULL,
    "region_code" TEXT,
    "applies_to_travel" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "tax_rates_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "brokerages_tenant_id_name_idx" ON "brokerages"("tenant_id", "name");

-- CreateIndex
CREATE INDEX "brokerages_tenant_id_created_at_idx" ON "brokerages"("tenant_id", "created_at");

-- CreateIndex
CREATE INDEX "clients_tenant_id_sort_name_id_idx" ON "clients"("tenant_id", "sort_name", "id");

-- CreateIndex
CREATE INDEX "clients_tenant_id_created_at_id_idx" ON "clients"("tenant_id", "created_at", "id");

-- CreateIndex
CREATE INDEX "clients_tenant_id_brokerage_id_idx" ON "clients"("tenant_id", "brokerage_id");

-- CreateIndex
CREATE INDEX "clients_tenant_id_phone_normalized_idx" ON "clients"("tenant_id", "phone_normalized");

-- CreateIndex
CREATE INDEX "clients_tenant_id_price_list_id_idx" ON "clients"("tenant_id", "price_list_id");

-- CreateIndex
CREATE INDEX "client_contacts_tenant_id_client_id_idx" ON "client_contacts"("tenant_id", "client_id");

-- CreateIndex
CREATE INDEX "client_tags_tenant_id_tag_id_idx" ON "client_tags"("tenant_id", "tag_id");

-- CreateIndex
CREATE INDEX "notes_tenant_id_client_id_created_at_idx" ON "notes"("tenant_id", "client_id", "created_at");

-- CreateIndex
CREATE INDEX "notes_tenant_id_brokerage_id_created_at_idx" ON "notes"("tenant_id", "brokerage_id", "created_at");

-- CreateIndex
CREATE INDEX "client_activities_tenant_id_client_id_occurred_at_idx" ON "client_activities"("tenant_id", "client_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "saved_views_tenant_id_entity_user_id_idx" ON "saved_views"("tenant_id", "entity", "user_id");

-- CreateIndex
CREATE INDEX "import_jobs_tenant_id_created_at_idx" ON "import_jobs"("tenant_id", "created_at");

-- CreateIndex
CREATE INDEX "export_jobs_tenant_id_created_at_idx" ON "export_jobs"("tenant_id", "created_at");

-- CreateIndex
CREATE INDEX "services_tenant_id_sort_order_idx" ON "services"("tenant_id", "sort_order");

-- CreateIndex
CREATE INDEX "service_variants_tenant_id_service_id_idx" ON "service_variants"("tenant_id", "service_id");

-- CreateIndex
CREATE INDEX "packages_tenant_id_sort_order_idx" ON "packages"("tenant_id", "sort_order");

-- CreateIndex
CREATE INDEX "add_ons_tenant_id_sort_order_idx" ON "add_ons"("tenant_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "property_types_tenant_id_key_key" ON "property_types"("tenant_id", "key");

-- CreateIndex
CREATE INDEX "size_bands_tenant_id_min_size_idx" ON "size_bands"("tenant_id", "min_size");

-- CreateIndex
CREATE INDEX "price_rules_tenant_id_item_kind_item_id_idx" ON "price_rules"("tenant_id", "item_kind", "item_id");

-- CreateIndex
CREATE INDEX "client_price_lists_tenant_id_name_idx" ON "client_price_lists"("tenant_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "client_price_list_items_tenant_id_price_list_id_item_kind_i_key" ON "client_price_list_items"("tenant_id", "price_list_id", "item_kind", "item_id");

-- CreateIndex
CREATE INDEX "territories_tenant_id_name_idx" ON "territories"("tenant_id", "name");

-- CreateIndex
CREATE INDEX "travel_fee_rules_tenant_id_priority_idx" ON "travel_fee_rules"("tenant_id", "priority");

-- CreateIndex
CREATE INDEX "coupons_tenant_id_created_at_idx" ON "coupons"("tenant_id", "created_at");

-- CreateIndex
CREATE INDEX "coupon_redemptions_tenant_id_coupon_id_client_id_idx" ON "coupon_redemptions"("tenant_id", "coupon_id", "client_id");

-- CreateIndex
CREATE INDEX "tax_rates_tenant_id_region_code_idx" ON "tax_rates"("tenant_id", "region_code");

-- AddForeignKey
ALTER TABLE "brokerages" ADD CONSTRAINT "brokerages_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "brokerages" ADD CONSTRAINT "brokerages_price_list_id_fkey" FOREIGN KEY ("price_list_id") REFERENCES "client_price_lists"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clients" ADD CONSTRAINT "clients_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clients" ADD CONSTRAINT "clients_brokerage_id_fkey" FOREIGN KEY ("brokerage_id") REFERENCES "brokerages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clients" ADD CONSTRAINT "clients_price_list_id_fkey" FOREIGN KEY ("price_list_id") REFERENCES "client_price_lists"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clients" ADD CONSTRAINT "clients_merged_into_id_fkey" FOREIGN KEY ("merged_into_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tags" ADD CONSTRAINT "tags_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_tags" ADD CONSTRAINT "client_tags_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_tags" ADD CONSTRAINT "client_tags_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_tags" ADD CONSTRAINT "client_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notes" ADD CONSTRAINT "notes_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notes" ADD CONSTRAINT "notes_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notes" ADD CONSTRAINT "notes_brokerage_id_fkey" FOREIGN KEY ("brokerage_id") REFERENCES "brokerages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notes" ADD CONSTRAINT "notes_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_views" ADD CONSTRAINT "saved_views_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_views" ADD CONSTRAINT "saved_views_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_jobs" ADD CONSTRAINT "import_jobs_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_jobs" ADD CONSTRAINT "import_jobs_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "export_jobs" ADD CONSTRAINT "export_jobs_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "export_jobs" ADD CONSTRAINT "export_jobs_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skills" ADD CONSTRAINT "skills_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "services" ADD CONSTRAINT "services_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "services" ADD CONSTRAINT "services_required_skill_id_fkey" FOREIGN KEY ("required_skill_id") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_variants" ADD CONSTRAINT "service_variants_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_variants" ADD CONSTRAINT "service_variants_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packages" ADD CONSTRAINT "packages_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "package_items" ADD CONSTRAINT "package_items_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "package_items" ADD CONSTRAINT "package_items_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "package_items" ADD CONSTRAINT "package_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "service_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "add_ons" ADD CONSTRAINT "add_ons_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "add_ons" ADD CONSTRAINT "add_ons_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "property_types" ADD CONSTRAINT "property_types_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "size_bands" ADD CONSTRAINT "size_bands_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_size_band_id_fkey" FOREIGN KEY ("size_band_id") REFERENCES "size_bands"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_property_type_id_fkey" FOREIGN KEY ("property_type_id") REFERENCES "property_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_price_lists" ADD CONSTRAINT "client_price_lists_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_price_list_items" ADD CONSTRAINT "client_price_list_items_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_price_list_items" ADD CONSTRAINT "client_price_list_items_price_list_id_fkey" FOREIGN KEY ("price_list_id") REFERENCES "client_price_lists"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "territories" ADD CONSTRAINT "territories_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "travel_fee_rules" ADD CONSTRAINT "travel_fee_rules_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "travel_fee_rules" ADD CONSTRAINT "travel_fee_rules_territory_id_fkey" FOREIGN KEY ("territory_id") REFERENCES "territories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tax_rates" ADD CONSTRAINT "tax_rates_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------------------------
-- Search: generated columns (SQL-only, not in schema.prisma) with trigram + full-text indexes
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "clients" ADD COLUMN "search_text" text GENERATED ALWAYS AS (
  lower(coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(email, '') || ' ' ||
        coalesce(phone_normalized, '') || ' ' || coalesce(company, '') || ' ' || coalesce(external_ref, ''))
) STORED;
ALTER TABLE "clients" ADD COLUMN "search_vector" tsvector GENERATED ALWAYS AS (
  to_tsvector('simple'::regconfig, coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' ||
              coalesce(email, '') || ' ' || coalesce(company, ''))
) STORED;
ALTER TABLE "brokerages" ADD COLUMN "search_text" text GENERATED ALWAYS AS (
  lower(coalesce(name, '') || ' ' || coalesce(email, '') || ' ' || coalesce(city, ''))
) STORED;

CREATE INDEX "clients_search_trgm_idx" ON "clients" USING gin ("tenant_id", "search_text" gin_trgm_ops) WHERE deleted_at IS NULL;
CREATE INDEX "clients_search_fts_idx" ON "clients" USING gin ("tenant_id", "search_vector") WHERE deleted_at IS NULL;
CREATE INDEX "brokerages_search_trgm_idx" ON "brokerages" USING gin ("tenant_id", "search_text" gin_trgm_ops) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- Uniqueness among live rows, and integrity checks
-- ---------------------------------------------------------------------------------------------
CREATE UNIQUE INDEX "clients_email_live_key" ON "clients" ("tenant_id", "email") WHERE deleted_at IS NULL AND email IS NOT NULL;
CREATE UNIQUE INDEX "clients_external_ref_live_key" ON "clients" ("tenant_id", "external_ref") WHERE deleted_at IS NULL AND external_ref IS NOT NULL;
CREATE UNIQUE INDEX "brokerages_name_live_key" ON "brokerages" ("tenant_id", lower("name")) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX "brokerages_external_ref_live_key" ON "brokerages" ("tenant_id", "external_ref") WHERE deleted_at IS NULL AND external_ref IS NOT NULL;
CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("tenant_id", lower("name"));
CREATE UNIQUE INDEX "skills_name_live_key" ON "skills" ("tenant_id", lower("name")) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX "coupons_code_live_key" ON "coupons" ("tenant_id", "code") WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX "price_rules_item_band_type_key" ON "price_rules" ("tenant_id", "item_kind", "item_id", "size_band_id", "property_type_id") NULLS NOT DISTINCT;

ALTER TABLE "clients" ADD CONSTRAINT "clients_email_lowercase" CHECK (email = lower(email));
ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_email_lowercase" CHECK (email = lower(email));
ALTER TABLE "notes" ADD CONSTRAINT "notes_one_subject" CHECK (num_nonnulls(client_id, brokerage_id) = 1);
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_code_upper" CHECK (code = upper(code));
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_value" CHECK (
  (kind = 'percent' AND percent_off_bps BETWEEN 1 AND 10000 AND amount_off IS NULL) OR
  (kind = 'fixed' AND amount_off > 0 AND percent_off_bps IS NULL));
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_dates" CHECK (starts_at IS NULL OR expires_at IS NULL OR expires_at > starts_at);
ALTER TABLE "client_price_list_items" ADD CONSTRAINT "client_price_list_items_one_value" CHECK (num_nonnulls(fixed_price, percent_off_bps) = 1);
ALTER TABLE "client_price_list_items" ADD CONSTRAINT "client_price_list_items_ranges" CHECK (coalesce(fixed_price, 0) >= 0 AND coalesce(percent_off_bps, 0) BETWEEN 0 AND 10000);
ALTER TABLE "client_price_lists" ADD CONSTRAINT "client_price_lists_bps" CHECK (default_percent_off_bps BETWEEN 0 AND 10000);
ALTER TABLE "tax_rates" ADD CONSTRAINT "tax_rates_bps" CHECK (rate_bps BETWEEN 0 AND 10000);
ALTER TABLE "service_variants" ADD CONSTRAINT "service_variants_price" CHECK (base_price >= 0);
ALTER TABLE "packages" ADD CONSTRAINT "packages_price" CHECK (base_price >= 0);
ALTER TABLE "add_ons" ADD CONSTRAINT "add_ons_price" CHECK (base_price >= 0);
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_price" CHECK (price >= 0);
ALTER TABLE "size_bands" ADD CONSTRAINT "size_bands_range" CHECK (min_size >= 0 AND (max_size IS NULL OR max_size > min_size));
ALTER TABLE "size_bands" ADD CONSTRAINT "size_bands_no_overlap"
  EXCLUDE USING gist ("tenant_id" WITH =, int4range("min_size", "max_size", '[)') WITH &&) WHERE (deleted_at IS NULL);
ALTER TABLE "travel_fee_rules" ADD CONSTRAINT "travel_fee_rules_shape" CHECK (
  (kind = 'territory' AND territory_id IS NOT NULL AND fee >= 0) OR
  (kind = 'distance' AND free_km >= 0 AND per_km >= 0 AND coalesce(min_fee, 0) >= 0 AND coalesce(max_fee, 0) >= 0));

-- ---------------------------------------------------------------------------------------------
-- Composite tenant-scoped foreign keys (defence in depth against cross-tenant references)
-- ---------------------------------------------------------------------------------------------
CREATE UNIQUE INDEX "brokerages_tenant_id_id_key" ON "brokerages" ("tenant_id", "id");
CREATE UNIQUE INDEX "clients_tenant_id_id_key" ON "clients" ("tenant_id", "id");
CREATE UNIQUE INDEX "tags_tenant_id_id_key" ON "tags" ("tenant_id", "id");
CREATE UNIQUE INDEX "client_price_lists_tenant_id_id_key" ON "client_price_lists" ("tenant_id", "id");
CREATE UNIQUE INDEX "skills_tenant_id_id_key" ON "skills" ("tenant_id", "id");
CREATE UNIQUE INDEX "services_tenant_id_id_key" ON "services" ("tenant_id", "id");
CREATE UNIQUE INDEX "service_variants_tenant_id_id_key" ON "service_variants" ("tenant_id", "id");
CREATE UNIQUE INDEX "packages_tenant_id_id_key" ON "packages" ("tenant_id", "id");
CREATE UNIQUE INDEX "size_bands_tenant_id_id_key" ON "size_bands" ("tenant_id", "id");
CREATE UNIQUE INDEX "property_types_tenant_id_id_key" ON "property_types" ("tenant_id", "id");
CREATE UNIQUE INDEX "territories_tenant_id_id_key" ON "territories" ("tenant_id", "id");
CREATE UNIQUE INDEX "coupons_tenant_id_id_key" ON "coupons" ("tenant_id", "id");
ALTER TABLE "clients" ADD CONSTRAINT "clients_brokerage_id_tscope_fkey" FOREIGN KEY ("tenant_id", "brokerage_id") REFERENCES "brokerages" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "clients" ADD CONSTRAINT "clients_price_list_id_tscope_fkey" FOREIGN KEY ("tenant_id", "price_list_id") REFERENCES "client_price_lists" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "clients" ADD CONSTRAINT "clients_merged_into_id_tscope_fkey" FOREIGN KEY ("tenant_id", "merged_into_id") REFERENCES "clients" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "brokerages" ADD CONSTRAINT "brokerages_price_list_id_tscope_fkey" FOREIGN KEY ("tenant_id", "price_list_id") REFERENCES "client_price_lists" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_client_id_tscope_fkey" FOREIGN KEY ("tenant_id", "client_id") REFERENCES "clients" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "client_tags" ADD CONSTRAINT "client_tags_client_id_tscope_fkey" FOREIGN KEY ("tenant_id", "client_id") REFERENCES "clients" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "client_tags" ADD CONSTRAINT "client_tags_tag_id_tscope_fkey" FOREIGN KEY ("tenant_id", "tag_id") REFERENCES "tags" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "notes" ADD CONSTRAINT "notes_client_id_tscope_fkey" FOREIGN KEY ("tenant_id", "client_id") REFERENCES "clients" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "notes" ADD CONSTRAINT "notes_brokerage_id_tscope_fkey" FOREIGN KEY ("tenant_id", "brokerage_id") REFERENCES "brokerages" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_client_id_tscope_fkey" FOREIGN KEY ("tenant_id", "client_id") REFERENCES "clients" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "services" ADD CONSTRAINT "services_required_skill_id_tscope_fkey" FOREIGN KEY ("tenant_id", "required_skill_id") REFERENCES "skills" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "service_variants" ADD CONSTRAINT "service_variants_service_id_tscope_fkey" FOREIGN KEY ("tenant_id", "service_id") REFERENCES "services" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "package_items" ADD CONSTRAINT "package_items_package_id_tscope_fkey" FOREIGN KEY ("tenant_id", "package_id") REFERENCES "packages" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "package_items" ADD CONSTRAINT "package_items_variant_id_tscope_fkey" FOREIGN KEY ("tenant_id", "variant_id") REFERENCES "service_variants" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "add_ons" ADD CONSTRAINT "add_ons_service_id_tscope_fkey" FOREIGN KEY ("tenant_id", "service_id") REFERENCES "services" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_size_band_id_tscope_fkey" FOREIGN KEY ("tenant_id", "size_band_id") REFERENCES "size_bands" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "price_rules" ADD CONSTRAINT "price_rules_property_type_id_tscope_fkey" FOREIGN KEY ("tenant_id", "property_type_id") REFERENCES "property_types" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "client_price_list_items" ADD CONSTRAINT "client_price_list_items_price_list_id_tscope_fkey" FOREIGN KEY ("tenant_id", "price_list_id") REFERENCES "client_price_lists" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "travel_fee_rules" ADD CONSTRAINT "travel_fee_rules_territory_id_tscope_fkey" FOREIGN KEY ("tenant_id", "territory_id") REFERENCES "territories" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_coupon_id_tscope_fkey" FOREIGN KEY ("tenant_id", "coupon_id") REFERENCES "coupons" ("tenant_id", "id") ON DELETE RESTRICT;
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_client_id_tscope_fkey" FOREIGN KEY ("tenant_id", "client_id") REFERENCES "clients" ("tenant_id", "id") ON DELETE RESTRICT;

-- ---------------------------------------------------------------------------------------------
-- Row-level security: enabled, forced, tenant_isolation policy for tuello_app
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "brokerages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "brokerages" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "brokerages" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "clients" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "clients" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "clients" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "client_contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_contacts" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "client_contacts" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tags" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tags" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "client_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_tags" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "client_tags" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notes" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "notes" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "client_activities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_activities" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "client_activities" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "saved_views" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "saved_views" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "saved_views" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "import_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_jobs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "import_jobs" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "export_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "export_jobs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "export_jobs" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "skills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "skills" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "skills" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "services" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "services" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "service_variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_variants" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "service_variants" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "packages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "packages" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "packages" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "package_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "package_items" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "package_items" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "add_ons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "add_ons" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "add_ons" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "property_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "property_types" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "property_types" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "size_bands" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "size_bands" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "size_bands" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "price_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "price_rules" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "price_rules" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "client_price_lists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_price_lists" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "client_price_lists" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "client_price_list_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_price_list_items" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "client_price_list_items" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "territories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "territories" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "territories" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "travel_fee_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "travel_fee_rules" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "travel_fee_rules" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "coupons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coupons" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "coupons" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "coupon_redemptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coupon_redemptions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "coupon_redemptions" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));
ALTER TABLE "tax_rates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tax_rates" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tax_rates" TO tuello_app
  USING (tenant_id = (SELECT app.current_tenant_id()))
  WITH CHECK (tenant_id = (SELECT app.current_tenant_id()));

-- ---------------------------------------------------------------------------------------------
-- Privileges. Timeline and coupon redemptions are append-only for the app.
-- ---------------------------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON "brokerages", "clients", "client_contacts", "tags", "client_tags", "notes", "saved_views", "import_jobs", "export_jobs", "skills", "services", "service_variants", "packages", "package_items", "add_ons", "property_types", "size_bands", "price_rules", "client_price_lists", "client_price_list_items", "territories", "travel_fee_rules", "coupons", "tax_rates" TO tuello_app;
GRANT SELECT, INSERT ON "client_activities", "coupon_redemptions" TO tuello_app;
